#!/bin/sh
# skipcheck.sh -- gate for the PIPE_Q_SKIP path in pipe_side_prepare_q.
#
# WHAT IS GUARDED. A special-q whose exact norm will not fit BN_LIMBS*32 bits is
# passed over rather than sieved, and the band continues. That is a THIRD
# outcome threaded through run_pipeline_impl -- not success, not failure -- and
# it touches the async-upload drain, the checkpoint, the band summary and the
# PIPE_SKIP_MAX stop. None of it was exercised by any gate: `check` is CPU-only
# and every other pipeline test runs a width the job fits, so the whole path
# could rot silently and only a client running the wrong build would find out.
#
# WHY THE JOBS ARE GENERATED AND NOT CHECKED IN. The path only fires when the
# norm overflows THIS BUILD's width, so a fixed job pins the gate to a fixed
# BN_LIMBS -- and the default has already moved 8 -> 12 once. Worse, no single
# real job reaches all three cases. Measured 2026-09-04 on the c194 quintic in
# this tree, side 1 exceeds side 0 by 79-91 bits on all 40000 samples, and the
# bound is so tightly clustered (~220-240 bits) that BN_LIMBS=6 skips 100% of
# the band and BN_LIMBS=8 skips none: no width mixes, and none skips on side 0.
#
# WHICH SIDE SKIPS IS A PROPERTY OF THE JOB, not a constant. pipe_side_prepare_q
# checks side 1 FIRST and short-circuits, so side 0 only ever raises the skip on
# a job whose RATIONAL bound is the larger one -- and those exist. Two real SNFS
# polynomials, measured 2026-09-04 at logI 14, the geometry both would be sieved
# at:
#
#   40457117852617043370139^11-1, quintic, difficulty 226.07
#       algebraic 165.41 bits, rational 181.89 -- rational larger on 100% of
#       4000 samples. But no LEGAL width isolates side 0: at 128 both sides
#       cross (so side 1 skips first) and by 192 neither does. The side-0-only
#       window is 172-180 bits, which is not a multiple of 64.
#
#   3132056929538285020802183644638793612181421933816103^5-1, quartic,
#   difficulty 205.98, c4..c0 = 1 1 1 1 1, Y1 = -1
#       algebraic 133.52 bits, rational 203.80 -- a 70-bit gap -- and at
#       BN_LIMBS=6 normscan reports "over 192 bits: side1 only 0, side0 only
#       20000, both 0". This one DOES fire the side-0 path at a legal width.
#
# So the side-0 branch, and the drain written for it, is live code on real jobs.
# Neither is used here, because which side a fixed job skips on depends on the
# build width and this gate has to work at whatever width it is run at.
#
# The jobs are therefore built to order, with normscan -- the shipping tool,
# sharing norm_setup and qlat_build with the siever -- as the oracle that says
# the construction landed. Both families are genuine SNFS polynomials: n is set
# to F(Y0,Y1) exactly, so F(Y0,Y1) == 0 mod n holds by construction rather than
# by luck, and sqgen finds real roots.
#
#   side 0 driven:  x^4 + 1, Y0 = -2^e, Y1 = 1. Side 0's bound is the degree-1
#                   form's, ~log2|Y0| + a geometry constant, so e alone moves it
#                   while the tiny quartic keeps side 1 well under the limit.
#   side 1 driven:  c4*x^4 + 1 with c4 = 2^k and a small Y0, so the quartic's
#                   bound crosses the limit first and side 0 never does.
#
# NEEDS A CARD, so this is NOT in `check` -- same reason fbgpucheck is not.
set -e

BENCH=./bench
NORMSCAN=./normscan
[ -x "$BENCH" ]    || { echo "skipcheck: no $BENCH -- run make first"; exit 1; }
[ -x "$NORMSCAN" ] || { echo "skipcheck: no $NORMSCAN -- run make first"; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
fail=0

QMIN=15000000
SAMPLES=4000
# A SHORT band, and the tuning below is measured over THIS range, not over the
# whole 15M-225M one. The skip rate varies with q -- the first cut of this gate
# tuned over the full band, ran 2000 q worth at the bottom of it, and got 4
# skips where it wanted 47. Tune where you run.
QSPAN=2000
QHI=$((QMIN + QSPAN))
# Every case runs at logI 14: it is what these jobs would really be sieved at,
# and --region defaults to 14 and must not exceed logI, so logI 13 is refused
# before any sieving happens.

# ---------------------------------------------------------------- job builders
# rlim/alim are deliberately small: the norm bound does not depend on them, and
# a 225M factor base would dominate the gate's runtime for no coverage at all.
mkjob() {   # mkjob C4_EXP Y0_EXP FILE
    python3 - "$1" "$2" <<'PY' > "$3"
import sys
k, e = int(sys.argv[1]), int(sys.argv[2])
m = 2**e
c = [1, 0, 0, 0, 2**k]                          # c0..c4
n = sum(ci * ((-m)**i) for i, ci in enumerate(c))   # = F(Y0,Y1) with Y1 = 1
print("n: %d" % abs(n))
print("# generated by skipcheck.sh -- F(Y0,Y1) == 0 mod n by construction")
print("skew: 1.0")
for i, v in enumerate(c):
    print("c%d: %d" % (i, v))
print("Y0: %d" % (-m))
print("Y1: 1")
for key, val in [("rlim", 2000000), ("alim", 2000000), ("lpbr", 26),
                 ("lpba", 26), ("mfbr", 52), ("mfba", 52)]:
    print("%s: %s" % (key, val))
PY
}

# normscan's per-side over-limit split, as three numbers: side1-only side0-only both
scan() {    # scan FILE logI -> "s1 s0 both"
    # --windows 1: normscan's 40 windows each start at their own q0 and run to
    # qmax, so on a short band they overlap and re-sample -- 2336 "samples" from
    # a range holding 118 (q,rho). One window enumerates exactly what the band
    # will sieve, in order, which is the number this gate needs.
    out=$($NORMSCAN --poly "$1" --qmin $QMIN --qmax $QHI --logI "$2" \
                    --windows 1 --samples $SAMPLES 2>&1 || true)
    nsamp=$(echo "$out" | awk '/^  sampled /{print $2}')
    echo "$out" | awk -v ns="${nsamp:-0}" \
        '/over [0-9]+ bits: side1 only/ {print $6, $9, $11, ns; found=1}
         END {if (!found) print 0, 0, 0, ns}' | tr -d ','
}

# The build's own width, read back from normscan rather than assumed.
mkjob 0 100 "$TMP/probe.job"
LIMIT=$($NORMSCAN --poly "$TMP/probe.job" --qmin $QMIN --qmax $QHI --logI 14 \
                  --windows 1 --samples 200 2>&1 |
        grep -oE 'exceed [0-9]+ bits' | head -1 | awk '{print $2}')
[ -n "$LIMIT" ] || { echo "skipcheck: could not read the build's norm width"; exit 1; }
echo "  build width: $LIMIT bits (BN_LIMBS*32)"

# THIS IS A BN_LIMBS=4 GATE, and the reason is not squeamishness.
#
# To make a q overflow a W-bit type you need a job whose norms EXCEED W bits.
# The control path being tested is width-independent -- `continue` without
# advancing nqdone, the drain, the cap, the checkpoint -- so exercising it at one
# width covers it. What the width changes is whether such a job can be built and
# SIEVED, and past 128 bits it cannot be sieved cheaply:
#
#   * pipeline.cuh:2018 makes a special-q with no two-sided survivors FATAL, by
#     design. So the generated job must actually yield relations, not merely
#     overflow.
#   * A job that overflows 256 bits on one side has ~375 bits of norm across the
#     two. At toy bounds (lim 2e6, lpb 26) that yields no survivors at all and
#     the band dies; measured 2026-09-04 at BN_LIMBS=8. At bounds that would
#     yield -- lim 5e7 -- factor-base generation alone ran past 3.5 minutes
#     without reaching the sieve, which is not a gate.
#   * Separately, poly_t holds Y0, Y1 and each coefficient as an exact decimal
#     string in an 80-byte field (trial division factors the exact F(a,b), not
#     its logarithm), so no job file can carry |Y0| >= 10^79 ~ 2^262 at all.
#     poly_load refuses it by name rather than truncating. That caps any side-0
#     skip near 293 bits however much time you are willing to spend.
#
# At 128 bits the whole thing costs about a minute: norms ~250 bits total, which
# lim 2e6 / lpb 26 sieves happily (81169 relations over 114 q, measured).
#
# The exponent search below scales with LIMIT, so raising this bound is a matter
# of finding sievable bounds for the wider job, not of rewriting the search.
if [ "$LIMIT" -gt 128 ]; then
    echo "  SKIP: this gate is verified at BN_LIMBS=4 (128 bits); this build is"
    echo "        $LIMIT. A job that overflows $LIMIT bits has norms too large to"
    echo "        yield survivors at any bounds this gate can afford, and"
    echo "        pipeline.cuh:2018 makes a survivor-less q fatal."
    echo "        Rebuild with 'make BN_LIMBS=4' to run it."
    exit 0
fi

# ------------------------------------------------------------------- bisection
# Find the exponent that puts the skip rate in [lo,hi] percent on the wanted
# side. Integer exponents move the bound in ~1-bit steps, so this is a scan, not
# a true bisection, and it is bounded: 40 tries or the gate gives up and says so
# rather than running a job that does not actually skip.
find_exp() {  # find_exp WHICH(0|1) logI LO_PCT HI_PCT -> exponent, or empty
    which=$1; logi=$2; lo=$3; hi=$4
    # BOTH starts scale with LIMIT. Side 0's bound is ~log2|Y0| + ~31 bits of
    # geometry; side 1's is ~log2(c4) + ~107 at logI 14 (measured: at LIMIT=128
    # the winning exponent was 21). Anchoring side 1 at a constant 2 -- as the
    # first cut did -- caps its reachable bound near 145 bits, so the gate
    # silently worked only at BN_LIMBS=4 and failed hard at 6 and 8 with "no
    # side-1 exponent found".
    if [ "$which" = 0 ]; then start=$((LIMIT - 34)); else start=$((LIMIT - 120)); fi
    [ $start -lt 1 ] && start=1
    i=0
    while [ $i -lt 50 ]; do
        e=$((start + i))
        if [ "$which" = 0 ]; then mkjob 0 $e "$TMP/try.job"
        else                     mkjob $e $((LIMIT - 40)) "$TMP/try.job"; fi
        set -- $(scan "$TMP/try.job" $logi)
        s1=$1; s0=$2; both=$3; ns=$4
        [ "${ns:-0}" -gt 0 ] || { i=$((i + 1)); continue; }
        if [ "$which" = 0 ]; then got=$s0; other=$s1; else got=$s1; other=$s0; fi
        pct=$((100 * got / ns))
        # The wanted side must DOMINATE. Not "be the only one": at the rates
        # these cases need there is always a thin band of (q,rho) where both
        # bounds cross, and demanding zero would reject every usable exponent.
        # A few of those only cost coverage -- side 1 is checked first, so a
        # "both" q raises a side-1 skip -- so require them to be a small
        # minority and let the bench-side assertions count what actually fired.
        if [ $((other + both)) -le $((got / 20)) ] && \
           [ $pct -ge $lo ] && [ $pct -le $hi ]; then
            echo $e; return 0
        fi
        i=$((i + 1))
    done
    return 1
}

# ------------------------------------------------------------------ the cases
# Case A and B must NOT reach PIPE_SKIP_MAX -- the point of those two is that
# the band SURVIVES a skip and keeps sieving -- so their target rates are set
# well under 100 skips across the ~118 (q,rho) this range holds.
run_band() {   # run_band JOB logI EXTRA... -> writes $TMP/out, returns bench's status
    job=$1; logi=$2; shift 2
    # ckpt.h builds these off the .part name: .part.ckpt, .part.ckpt.tmp,
    # .part.recover[.tmp], .lock. Removing "$TMP/rel.txt.ckpt" deleted a path
    # that is never created, leaving a real sidecar from a case that hit
    # PIPE_SKIP_MAX to be read by the NEXT case, against a different job.
    rm -f "$TMP/rel.txt" "$TMP/rel.txt".part "$TMP/rel.txt".part.* \
          "$TMP/rel.txt".lock 2>/dev/null || true
    set +e
    $BENCH --pipeline --poly "$job" --logI "$logi" \
           --qrange $QMIN:$QHI --relations "$TMP/rel.txt" "$@" \
           > "$TMP/out" 2>&1
    st=$?
    set -e
    return $st
}

nskip_side() { grep -c "SKIPPED q=.*exact side-$1" "$TMP/out" 2>/dev/null || true; }
pass() { printf 'PASS   %-42s %s\n' "$1" "$2"; }
bad()  { printf 'FAIL   %-42s %s\n' "$1" "$2"; fail=1; }
info() { printf 'INFO   %-42s %s\n' "$1" "$2"; }

# ---- case A: consecutive side-1 skips, band survives -----------------------
E1=$(find_exp 1 14 10 60) || { echo "skipcheck: no side-1 exponent found"; exit 1; }
mkjob "$E1" $((LIMIT - 40)) "$TMP/side1.job"
echo "  side-1 job: c4 = 2^$E1, Y0 = -2^$((LIMIT - 40)), logI 14"
if run_band "$TMP/side1.job" 14; then
    s1=$(nskip_side 1); s0=$(nskip_side 0)
    tot=$(grep -oE '\*\* [0-9]+ special-q SKIPPED' "$TMP/out" | grep -oE '[0-9]+' | head -1)
    # The band summary header, NOT the `nq_session=` runlog record: that record
    # goes to the run log, not to stdout, so grepping the console for it fails
    # on a band that ran perfectly well.
    nqs=$(grep -oE '\-\-\- band of [0-9]+ special-q \-\-\-' "$TMP/out" | grep -oE '[0-9]+' | head -1)
    [ "${s1:-0}" -gt 0 ] && pass "A side-1 skips fired" "$s1 skips" \
                         || bad  "A side-1 skips fired" "none seen"
    # `-lt` with a positive s1, not `-le`: at s1 = s0 = 0 the -le form printed
    # PASS for a band that skipped nothing at all.
    { [ "${s1:-0}" -gt 0 ] && [ "${s0:-0}" -lt "${s1:-0}" ]; } \
        && pass "A side 1 is the skipping side" "side0 $s0 < side1 $s1" \
        || bad  "A side 1 is the skipping side" "side0 $s0 vs side1 $s1"
    [ "${tot:-0}" = "$((s1 + s0))" ] && pass "A summary count matches warnings" "$tot" \
                                     || bad  "A summary count matches warnings" "summary $tot vs $((s1 + s0))"
    [ "${nqs:-0}" -gt 0 ] && pass "A band continued past the skips" "$nqs q sieved" \
                          || bad  "A band continued past the skips" "nq_session=${nqs:-unset}"
    grep -q 'rebuild with `make BN_LIMBS=' "$TMP/out" \
        && pass "A skip names the width to rebuild at" "" \
        || bad  "A skip names the width to rebuild at" "no rebuild advice printed"
else
    bad "A band survives side-1 skips" "bench exited $?"
    tail -15 "$TMP/out" | sed 's/^/  | /'
fi

# ---- case B: side 0 skips AFTER side 1's transform and uploads are in flight
# This is the case the drain at the skip site exists for: side 1 has already
# launched k_transform and four async H2D copies out of pinned buffers when
# side 0 raises the skip, and nothing downstream will synchronise because the
# slab loop is never reached. A missing drain shows up here as a CUDA error
# reported against the NEXT q, or as corrupted small-sieve input.
E0=$(find_exp 0 14 5 60) || { echo "skipcheck: no side-0 exponent found"; exit 1; }
mkjob 0 "$E0" "$TMP/side0.job"
echo "  side-0 job: Y0 = -2^$E0, logI 14"
if run_band "$TMP/side0.job" 14; then
    s1=$(nskip_side 1); s0=$(nskip_side 0)
    nqs=$(grep -oE '\-\-\- band of [0-9]+ special-q \-\-\-' "$TMP/out" | grep -oE '[0-9]+' | head -1)
    [ "${s0:-0}" -gt 0 ] && pass "B side-0 skips fired" "$s0 skips" \
                         || bad  "B side-0 skips fired" "none seen"
    [ "${s0:-0}" -gt "${s1:-0}" ] && pass "B side 0 is the skipping side" "side0 $s0 > side1 $s1" \
                                  || bad  "B side 0 is the skipping side" "side0 $s0 vs side1 $s1"
    [ "${nqs:-0}" -gt 0 ] && pass "B band continued after the drain" "$nqs q sieved" \
                          || bad  "B band continued after the drain" "nq_session=${nqs:-unset}"
    grep -qiE 'CUDA error|unspecified launch|illegal (memory )?access' "$TMP/out" \
        && bad  "B no CUDA error after a side-0 skip" "$(grep -im1 'CUDA error' "$TMP/out")" \
        || pass "B no CUDA error after a side-0 skip" ""
else
    bad "B band survives side-0 skips" "bench exited $?"
    tail -15 "$TMP/out" | sed 's/^/  | /'
fi

# ---- case C: PIPE_SKIP_MAX ends the run cleanly ----------------------------
# A stop, not a crash: rc stays 0, the cofactor queue is flushed and a
# checkpoint is written, exactly like the stop-file path. Regressing this to
# `rc = -1` would throw away every queued relation and report the band FAILED.
# Long enough to reach PIPE_SKIP_MAX TWICE: case D measures the step a resume
# makes, and it cannot if the first cap already leaves the range nearly spent.
QHI=$((QMIN + 6000))
mkjob 0 $((LIMIT - 25)) "$TMP/all.job"
set -- $(scan "$TMP/all.job" 14)
# $4 is the literal "0" when normscan produced no sample line, and ${4:-1}
# substitutes only for unset/null -- so guard the divisor explicitly rather
# than letting `set -e` kill the gate on a division by zero. $1 counts too:
# a "both sides over" q raises a side-1 skip and is still a skip.
cap_n=$4; [ "${cap_n:-0}" -gt 0 ] || cap_n=0
if [ "$cap_n" -gt 0 ]; then
    echo "  cap job: Y0 = -2^$((LIMIT - 25)), logI 14, skip rate $(( 100 * ($1 + $2 + $3) / cap_n ))% of $cap_n q"
else
    echo "  cap job: Y0 = -2^$((LIMIT - 25)), logI 14 -- normscan returned no sample"
fi
if run_band "$TMP/all.job" 14 --cofactor; then
    pass "C cap stop is not a failure" "bench exited 0"
else
    bad "C cap stop is not a failure" "bench exited $?"
fi
grep -qE '\*\* [0-9]+ special-q skipped for norm width' "$TMP/out" \
    && pass "C cap warning printed" "$(grep -oE '\*\* [0-9]+ special-q skipped' "$TMP/out" | head -1)" \
    || bad  "C cap warning printed" "not seen"
grep -q 'FAILED' "$TMP/out" \
    && bad  "C band not reported FAILED" "$(grep -m1 FAILED "$TMP/out")" \
    || pass "C band not reported FAILED" ""
grep -qE 'Rerun the same command to resume at q=' "$TMP/out" \
    && pass "C checkpoint written at the cap" "$(grep -oE 'resume at q=[0-9]+' "$TMP/out" | head -1)" \
    || bad  "C checkpoint written at the cap" "no checkpoint line"

# ---- D: what a resume actually does after a cap stop -----------------------
# REPORTED, NOT ASSERTED. nqskip is not checkpointed, so a resumed band starts
# counting from zero and stops again PIPE_SKIP_MAX skips later. Whether that is
# acceptable is a policy question -- the comment at PIPE_SKIP_MAX already says
# the net has this hole -- so the gate measures the step size and leaves the
# judgement to a human rather than pinning a number nobody has decided on.
first=$(grep -oE 'resume at q=[0-9]+' "$TMP/out" | head -1 | cut -d= -f2)
if [ -n "$first" ]; then
    cp "$TMP/out" "$TMP/out.first"
    set +e
    $BENCH --pipeline --poly "$TMP/all.job" --logI 14 --qrange $QMIN:$QHI \
           --relations "$TMP/rel.txt" --cofactor > "$TMP/out" 2>&1
    set -e
    second=$(grep -oE 'resume at q=[0-9]+' "$TMP/out" | head -1 | cut -d= -f2)
    if [ -n "$second" ] && [ "$second" != "$first" ]; then
        info "D resume advances per cap stop" "q=$first -> q=$second, ~PIPE_SKIP_MAX q per run"
    elif [ "$second" = "$first" ]; then
        bad "D resume makes forward progress" "stuck at q=$first -- a resumed band cannot advance"
    else
        # No second checkpoint means the resumed band reached the end of the
        # range instead of capping again -- still forward progress, just not a
        # measurable step. Say which it was rather than leaving it ambiguous.
        if grep -q 'q range exhausted' "$TMP/out"; then
            info "D resume advances" "resumed at q=$first and ran the range out"
        else
            info "D resume behaviour" "second run wrote no checkpoint and did not finish"
        fi
    fi
    mv "$TMP/out.first" "$TMP/out"
fi

echo
if [ $fail -eq 0 ]; then echo "  skipcheck: all cases passed"; else echo "  skipcheck FAILED"; fi
exit $fail
